/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef message_CONSTANTS_H
#define message_CONSTANTS_H

#include "message_types.h"



class messageConstants {
 public:
  messageConstants();

};

extern const messageConstants g_message_constants;



#endif
