/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef myfirst_CONSTANTS_H
#define myfirst_CONSTANTS_H

#include "myfirst_types.h"



class myfirstConstants {
 public:
  myfirstConstants();

};

extern const myfirstConstants g_myfirst_constants;



#endif
